### PR TITLE
Move Connection from return to argument.

### PR DESCRIPTION
**Pull request by Neppord**
I hope this doesen't make the code to simple.

I want to make this change to easier replace the database depending on backend.

### CODE REVIEW

**Comment by Neppord** [comment]
OBS, i have not run the app, since i dont have a mysql server running. Please check before merge.

**Comment by martinsson** [comment]
Ok I resolved the conflict and tested it, but only then did I discover what you did. 

I can certainly see why this would make sens in the real world. Here however that move makes it harder to initiate tests for people doing the kata. It also introduces some sort of dependency injection which is part of the exercice. 

Wouldn't switching to sqllite just be changing two-ish lines in the prices.ts, add another sql file and a different runLocalDatabase.sh script?

**Comment by martinsson** [comment]
I pushed a branch with the conflict resolution: sqlliteByNeppord

**Comment by Neppord** [comment]
Thanks for taking the time!

I was unsure if I could just replace MySQL, I thought you wanted both.

**Comment by Neppord** [comment]
Is there any of the commits you would like to cherry pick, then you are welcome to do so. I would suggest the rename of index

**Comment by martinsson** [comment]
I doubt it is possible to have both. Even if it is It will complicate the
whole.

Also if we have a commit that switches to sqklite it is easy to test that
and revert if feedback shows that a real db would be better. But the more
the time passes the more I think that sqklite is the best

**Pull request closed without merging**
