### PR TITLE
Replaced mysql with sqlite

### PR DESCRIPTION
**Pull request by Neppord**
All tests pass.

I have not tested the app on a fresh windows machine. I think it would work but since i have installed additional sqlite tools i cant be sure.

I have also simplified the setup of the database, so that the createApp also creates the database and runs the init script on it, which now is idempotent.

### CODE REVIEW

**Comment by martinsson** [comment]
Hmm, it breaks the wallaby config due to the fact that it can't see files outside the typescript folder 
https://github.com/wallabyjs/public/issues/68

I could put wallaby config file in the root folder but that would be noisy with regard to other languages.

Now there's another thing: it is a bit wierd to have the application boot inject it's own data. I'm afraid that's going to confuse people. I think it is preferable to have a script do the job like before. If it is a script people will either have to install sqllite executable or it could be a build-tool command. I guess a build-tool command would be the best, WDYT?

**Comment by codecop** [comment]
It would be great to have all SQL's to be standard and work across all databases. Are the updated statements more standard or just Sqllite specific? I had similar problems with HSqlDb (Java) and gave up.

**Comment by Neppord** [comment]
@codecop i changed to it, because the old version of replace that was used in the price.ts file did not work on sqlite. it is possible that its more portable but i don't know.

@martinsson i have now moved the init code into its own file, and added a `npm run init-database`

**Comment by martinsson** [comment]
Great, thanks

**Pull request merged**
