### PR TITLE
Replace mysql with sqllite

### PR DESCRIPTION
**Pull request by martinsson**
From PR #13 

Only implented for TS.
This would probably make the setup quicker - removing the need for docker alltogether

### CODE REVIEW

**Comment by codecop** [comment]
We cant change the `initDatabase.sql` because that is used by all other languages to initialize MySQL. Needs to be specific file locally to the language.

I see the pain during setup and I really like the MySQL real database.
Could this code be in a separate folder, e.g. `typescript-sqlite`, like other katas have `js-jasmine` and `js-mocha` starting points? 

I could add java-hsqldb in a similar way later.

**Comment by martinsson** [comment]
Indeed this cannot be merged as is. 

Do you prefer mysql over sqlite? Does it have more value in some way? 

We can 
1. replace mysql with sqllite
2. create technology specific implementations 
3. create indirection so that every language can choose.
4. stay with mysql.

I'm afraid 2. would quickly make any improvements to the core impossible due to too much duplication. Option 3 isn't great because that makes the code less hard-coded which is one of the main values of the kata.

I'm open for 1 or 4 as options.

**Comment by codecop** [comment]
I would like 4 and still want to value Sam's work

**Comment by ygrenzinger** [comment]
Just for information, it works quickly in Java by adding in pom.xm:
`        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.199</version>
        </dependency>
`
And creating the connection like this : 
`
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:sample;MODE=MYSQL;INIT=RUNSCRIPT FROM 'classpath:script/initDatabase.sql'");
        ds.setUser("sa");
        ds.setPassword("sa");
        Connection connection = ds.getConnection();
`

**Comment by martinsson** [comment]
H2 will work smothly for jvm languages, not necessarily for others.  Could we use H2 for other languages? Could we make the injection of data work for other languages?

One option might be to use a different database for different languages.

Another interesting option that @Fabinout suggested would be to have an online, already populated, DB with read only rights.

**Comment by ygrenzinger** [comment]
Yes it could be a very good idea !
And it would remove the put prices endpoint :)

**Comment by codecop** [comment]
This idea has not been discussed or worked on in past 4 years. Closing

**Pull request closed without merging**
