### PR TITLE
Script to start and initialize the database

### PR DESCRIPTION
**Pull request by bastiendavid**
Hello,

I added a script to start and initialize the database.

You may want to squash the 2 commits in one when merging.

### CODE REVIEW

**Comment by martinsson** [comment]
Thanks. Just one thing, I'm not sure it's very safe to delete the docker of name mariadb every time.

**Comment by bastiendavid** [comment]
Agreed.
Maybe we can ask for a confirmation before deleting it?
Or do you have a better alternative to suggest?

**Comment by martinsson** [comment]
Perhaps check if it exists and just starting it. Then use a database name that is specific so we don't crush any data

**Comment by bastiendavid** [comment]
Ok cool.
I’ll work on that and submit it tomorrow.

**Comment by martinsson** [comment]
Great. I changed the database name for now

**Pull request merged**
