### PR TITLE
csharp-simple and make with_tests consistent with main.

### PR DESCRIPTION
**Pull request by codecop**
Make java-simple working, add csharp-simple and minor additions to make both branches as similar as possible (besides tests).

### CODE REVIEW

**Comment by codecop** [comment]
These two build breaks are weird. Builds were working on my branch. "Error: Resource not accessible by integration" - what does that mean?

**Comment by martinsson** [comment]
I have no idea. I'm going to rerun the workflows for both the source and destination branches to at least see if results are consistent

**Comment by codecop** [comment]
Johan, I asked Roland who created the original build scripts and he is unable to find any issues. The build runs fine locally. We both ask you to accept the PR and hope that it will work. Please advise

**Comment by codecop** [comment]
I hope the permissions are only related to PR. I will merge an seen what is happening.

**Pull request merged**
